#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['cam_tests.cpp'] + bld.path.ant_glob('src/**/*.cpp'),
    target='cam_tests',
    use=['gtest', 'cam', 'nalu_includes'])
