#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='write_file.cpp',
            target='write_file',
            use=['c4m_includes', 'boost_includes', 'boost_system', 'sak'])
